const data = [
  "Dentista",
  "Astronauta",
  "Granjero",
  "Payaso",
  "Arqueólogo",
  "Chef",
  "Fotógrafo",
  "Buzo",
  "Bombero",
  "Pintor",
  "Cirujano",
  "Electricista",
  "Peluquero",
  "Taxista",
  "Director de cine",
  "Bailarín de ballet",
  "Director de orquesta",
  "Luchador de sumo",
  "Maestro de escuela",
  "Jugador de fútbol",
  "Cantante de ópera",
  "Juez",
  "Capitán de barco",
  "Cazador",
  "Boxeador",
  "Periodista",
  "Mago",
  "Conductor de tren",
  "Hombre lobo",
  "Monje",
  "Entrenador de gimnasio",
  "Escultor",
  "Director de teatro",
  "Astrólogo",
  "Político",
  "Científico loco",
  "Bruja",
  "Karateka",
  "Vaquero",
  "Payaso triste",
  "Hada madrina",
  "Buzo de búsqueda del tesoro",
  "Guardia de seguridad",
  "Estrella de rock",
  "Superhéroe",
  "Rey",
  "Reina",
  "Princesa",
  "Cazador de vampiros",
  "Zombie",
  "Pirata",
  "Vendedor de helados",
  "Astronauta en la luna",
  "Malabarista",
  "Director de circo",
  "Mimo",
  "Abogado",
  "Modelo de pasarela",
  "Chef de sushi",
  "Guardia real",
  "Director de banco",
  "Cantante de country",
  "Comediante",
  "Fotógrafo de moda",
  "Hombre de las cavernas",
  "Espía",
  "Guardabosques",
  "Director de aeropuerto",
  "Payaso de rodeo",
  "Modelo de revista",
  "Artista de graffiti",
  "Patinador",
  "Esquiador",
  "Instructor de yoga",
  "Genio de la lámpara",
  "Explorador",
  "Cantante de rap",
  "DJ",
  "Guerrero samurái",
  "Baterista de rock",
  "Prisionero escapando",
  "Caballero medieval",
  "Escalador de montañas",
  "Director de hotel",
  "Caballo de carreras",
  "Director de escuela de música",
  "Sastre",
  "Director de circo",
  "Líder de banda militar",
  "Presentador de noticias",
  "Lector de noticias loco",
  "Biólogo marino",
  "Mago oscuro",
  "Karateka",
  "Vaquero del Lejano Oeste",
  "Luchador de lucha libre",
  "Oso polar",
  "Foca",
  "Conejito",
  "Zorro",
  "Elefante",
  "Jirafa",
  "Canguro",
  "Tigre",
  "León",
  "Pingüino",
  "Delfín",
  "Serpiente",
  "Gorila",
  "Rana",
  "Cisne",
  "Cocodrilo",
  "Murciélago",
  "Pato",
  "Pollo",
  "Vaca",
  "Oveja",
  "Cabra",
  "Cerdito",
  "Ardilla",
  "Oso",
  "Pájaro carpintero",
  "Hormiga",
  "Abeja",
  "Mariposa",
  "Caracol",
  "Mariquita",
  "Araña",
  "Grillo",
  "Cucaracha",
  "Escarabajo",
  "Gusano",
  "Cangrejo",
  "Pulpo",
  "Calamar",
  "Medusa",
  "Tiburón",
  "Ballena",
  "Narval",
  "Caballito de mar",
  "Pez payaso",
  "Pez espada",
  "Estrella de mar",
  "Pulga de agua",
  "Caballito de mar",
  "Erizo de mar",
  "Esponja de mar",
  "Alga marina",
  "Medusa",
  "Foca",
  "Oso polar",
  "Pájaro carpintero",
  "Gaviota",
  "Flamenco",
  "Loro",
  "Pavo",
  "Avestruz",
  "Pavo real",
  "Cuervo",
  "Águila",
  "Pájaro carpintero",
  "Lechuza",
  "Halcón",
  "Paloma",
  "Buitre",
  "Cuervo",
  "Colibrí",
  "Murciélago",
  "Lobo",
  "Zorro",
  "León",
  "Tigre",
  "Pantera",
  "Lince",
  "Guepardo",
  "Oso pardo",
  "Panda",
  "Koala",
  "Canguro",
  "Wallaby",
  "Ornitorrinco",
  "Oso hormiguero",
  "Armadillo",
  "Puercoespín",
  "Castor",
  "Nutria",
  "Lince",
  "Puma",
  "Gacela",
  "Antílope",
  "Cebra",
  "Rinoceronte",
  "Hipopótamo",
  "Elefante",
  "Jirafa",
  "Camello",
  "Dromedario",
  "Cebra",
  "Cocodrilo",
  "Serpiente",
];

export default data;
